server:
  port: 8081
  servlet:
    context-path: /parking_space_service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: parking-space-service
  config:
    import: "configserver:"
  datasource:
    url: jdbc:mysql://localhost:3306/parking_db?createDatabaseIfNotExist=true
    username: root
    password: Ijse@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
