server:
  port: 8082
  servlet:
    context-path: /payment_service

spring:
  application:
    name: payment-service
  config:
    import: "configserver:"
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true
    username: root
    password: Ijse@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
